<?php

namespace AppBundle\Repository;

/**
 * AuteursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuteursRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function searchAuteur($nom, $prenom) {
        $em = $this->getEntityManager();

        $query = $em->createQuery('
        SELECT p FROM AppBundle:Auteurs p 
        WHERE p.nom LIKE :nom AND p.prenoms LIKE :prenom    
        ORDER BY p.nom ASC 
    ')
                ->setParameter('nom','%'. strtoupper($nom).'%')
                ->setParameter('prenom', '%'.strtoupper($prenom).'%');

        $auteur = $query->getResult();
        return $auteur;
    }
}
