<?php

namespace AppBundle\Repository;

/**
 * entiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class entiteRepository extends \Doctrine\ORM\EntityRepository
{
}
