<?php

namespace AppBundle\Repository;

/**
 * fichierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class fichierRepository extends \Doctrine\ORM\EntityRepository
{
}
