<?php

namespace AppBundle\Repository;

/**
 * LigneAuteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LigneAuteurRepository extends \Doctrine\ORM\EntityRepository
{
}
