<?php

namespace AppBundle\Repository;

/**
 * lolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class lolRepository extends \Doctrine\ORM\EntityRepository
{
}
